Translate Integrity
GraphQL-China/principled-graphql pull request #2
Opened 2019-02-24 19:55 UTC by ydfzgyj

目录在 Overview 中

2019-02-26 06:28 UTC, jonirrings requested changes
整体而言棒棒哒。

2019-02-26 06:28 UTC, jonirrings commented on src/content/pages/integrity.md
> +如果没有高度专业化的基础结构，单片架构很难扩展，数据图也不例外。不应当在单个代码库中实现组织的整个数据图这一层，而是应当在多个团队之间划分定义和实现图的职责。每个团队都应当负责维护公开其数据和服务的那一部分 schema，同时具有独立开发和在自己的发布周期中运行的灵活性。
Monolithic architecture 翻译成 单体架构 好一点吧？

2019-02-26 06:33 UTC, ydfzgyj commented on src/content/pages/integrity.md
> +如果没有高度专业化的基础结构，单片架构很难扩展，数据图也不例外。不应当在单个代码库中实现组织的整个数据图这一层，而是应当在多个团队之间划分定义和实现图的职责。每个团队都应当负责维护公开其数据和服务的那一部分 schema，同时具有独立开发和在自己的发布周期中运行的灵活性。
嗯嗯

2019-02-27 04:40 UTC, jonirrings approved these changes
nice work

2019-02-27 04:40 UTC, merged