Translate Agility and Operations
GraphQL-China/principled-graphql pull request #4
Opened 2019-03-27 17:06 UTC by jonirrings

2019-03-28 04:14 UTC, ydfzgyj requested changes
提了一些标点和格式上的小问题

2019-03-28 04:14 UTC, ydfzgyj commented on src/content/pages/agility.md
> +GraphQL 的一大价值就是在服务和消费者之间提供了一个抽象层，因此 schema 就不该与特定服务实现或者特定现存消费者强耦合。通过将实现细节从 schema 中分离，就能重构实现图关系的服务的同时 —— 例如，从单体架构切换到微服务架构，或者切换服务的实现语言 —— 而不用再次分发应用。同样地，schema 也不应该和特定应用取数据的方法所耦合。如果新的应用与旧的十分相似，那么应该只需要微
是 `disturbing apps` 不是 `distribute apps`，是不是看错了

2019-03-28 04:14 UTC, ydfzgyj commented on src/content/pages/agility.md
> +有件十分有诱惑力的事：提前定义你所有数据的"完美 schema"。然而，真正让一个 schema 产生价值的是与用户的需求一致，但这个在当前永远不知道的而且还会一直变化。真正通向"完美 schema"的方式是构建易于跟随实际需求变化而进化的图关系。
“但这个在当前永远不知道的而且还会一直变化” 有点读不通哈

2019-03-28 04:14 UTC, ydfzgyj commented on src/content/pages/agility.md
> +图关系的更新应该是一个持续的过程。相比较周期性的发布新"版本"的图关系（例如每 6 个月或者 12 个月），更好的是必要情况下能够一天修改多次。新字段可以在任何时间添加。而移除字段，则需要先将其标记为弃用，然后等到没有消费者在使用它的时候再移除。Schema 注册表使得图关系的敏捷演进成为可能，通过相关的流程和工具，可以让每个人都知晓影响他们的字段变更。这样就能保证只有全面审查过的变成才能进入生
这样就能保证只有全面审查过的“变更”才能进入生产环境
另外这里的变更会不会被误解成 mutation 啊，要不要换个词

2019-03-28 04:14 UTC, ydfzgyj commented on src/content/pages/agility.md
> +* 开发者能就在他们编辑器中得到所有可用图数据和服务的实时文档，且总是最新的
缺个句号

2019-03-28 04:14 UTC, ydfzgyj commented on src/content/pages/agility.md
> +* 当应用程序使用TypeScript、Java或Swift等带类型的语言开发时，类型信息可以从服务的类型声明一直传播到应用程序中的每行代码，从而确保全栈的类型正确性和错误信息的即时反馈。
中英文空格

2019-03-28 04:14 UTC, ydfzgyj commented on src/content/pages/operations.md
> +数据图中的授权具有两个同等重要的方面：访问控制，其指示允许用户访问的对象和字段;以及需求控制，其指示允许用户访问这些资源的方式（以及多少）。虽然经常被提及是访问控制，但是也需要注意需求控制，因为它在 GraphQL 的任何生产部署中都至关重要。允许用户执行任何可能的查询而不考虑成本是错误的，这会导致无法管理其对生产系统的影响。无论执行访问还是需求控制都必须在充分了解数据图的语义和性能的情况下才执
分号可以改成中文的

2019-03-28 04:14 UTC, ydfzgyj commented on src/content/pages/operations.md
> +图关系操作的记录称为**追踪**。追踪应该在一个地方汇集有关操作的所有相关信息，包括业务信息（谁执行的操作，访问或更改的内容，由哪位开发者构建的应用的哪一个功能，是否成功，执行效果如何）以及纯技术信息（哪个后端服务被调用，每个服务如何导致延迟，是否使用了缓存）。
这边的逗号应该都可以用顿号

2019-03-28 04:14 UTC, ydfzgyj commented on src/content/pages/agility.md
> +* 一个查询的成本估计（延迟或者服务器资源）能在开发者打这个查询后就给出，基于实时的生产数据。
能在开发者“键入”这个查询后就给出

2019-03-28 04:14 UTC, ydfzgyj commented on src/content/pages/operations.md
> +* 根据API使用情况为合作伙伴生成发票，以及可以根据访问的特定字段或消耗的资源生成详细的成本模型
API 前后加空格

2019-03-28 15:27 UTC, jonirrings commented on src/content/pages/agility.md
> +GraphQL 的一大价值就是在服务和消费者之间提供了一个抽象层，因此 schema 就不该与特定服务实现或者特定现存消费者强耦合。通过将实现细节从 schema 中分离，就能重构实现图关系的服务的同时 —— 例如，从单体架构切换到微服务架构，或者切换服务的实现语言 —— 而不用再次分发应用。同样地，schema 也不应该和特定应用取数据的方法所耦合。如果新的应用与旧的十分相似，那么应该只需要微
😊好呢

2019-03-30 08:18 UTC, jonirrings commented
@ydfzgyj 已修正，有劳再次审核。

2019-03-31 17:44 UTC, ydfzgyj requested changes

2019-03-31 17:44 UTC, ydfzgyj commented on src/content/pages/agility.md
> +* 能在开发者“键入”这个查询后，就在他们的编辑器中给出所用图数据和服务的实时文档，且总是最新的。
这个引号不用加的，是我为了强调用的……我下次换成加粗吧哈哈哈

2019-04-01 06:17 UTC, jonirrings commented on src/content/pages/agility.md
> +* 能在开发者“键入”这个查询后，就在他们的编辑器中给出所用图数据和服务的实时文档，且总是最新的。
Ok，修掉了。有劳再检查看看那儿有不通顺的。

2019-04-01 06:53 UTC, ydfzgyj approved these changes
Good Job!

2019-04-01 06:56 UTC, merged